# Generated by Django 5.2.5 on 2025-10-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gear_images/'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
