# Generated by Django 5.2.6 on 2025-10-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('hockey', 'Hockey'), ('curling', 'Curling'), ('ice_skating', 'Ice Skating'), ('apparel', 'Apparel'), ('accessories', 'Accessories'), ('protective_gear', 'Protective Gear'), ('other', 'Other')], max_length=20),
        ),
    ]
