# Generated by Django 5.2.6 on 2025-10-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0002_remove_rental_items_rental_total_cost_rental_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
