# Generated by Django 5.2.5 on 2025-10-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0003_cartitem_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('hockey', 'Hockey'), ('curling', 'Curling'), ('apparel', 'Apparel'), ('accessories', 'Accessories'), ('protective_gear', 'Protective Gear'), ('other', 'Other')], max_length=20),
        ),
    ]
