# Generated by Django 5.2.7 on 2025-10-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0004_auto_20251024_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='size',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='stock',
        ),
        migrations.AddField(
            model_name='gear',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
