# Generated by Django 5.2.7 on 2025-10-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0004_alter_gear_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
