# Generated by Django 5.2.7 on 2025-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0005_remove_gear_image_remove_gear_size_remove_gear_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
