# Generated by Django 5.2.7 on 2025-10-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0005_gear_is_featured'),
        ('rental_gear', '0006_add_stock_to_gear'),
    ]

    operations = [
    ]
