# Generated by Django 5.2.7 on 2025-10-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_gear', '0007_merge_0005_gear_is_featured_0006_add_stock_to_gear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='is_featured',
        ),
    ]
