# Generated by Django 5.2.6 on 2025-10-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='is_upvote',
            field=models.BooleanField(default=True),
        ),
    ]
