# Generated by Django 5.2.6 on 2025-10-25 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='upvote',
            name='unique_vote_per_user_post',
        ),
        migrations.RemoveConstraint(
            model_name='upvote',
            name='unique_vote_per_user_reply',
        ),
        migrations.AddField(
            model_name='upvote',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='upvote',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', True), ('user__isnull', False)), fields=('user', 'post'), name='unique_vote_per_user_post'),
        ),
        migrations.AddConstraint(
            model_name='upvote',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', True), ('user__isnull', False)), fields=('user', 'reply'), name='unique_vote_per_user_reply'),
        ),
        migrations.AddConstraint(
            model_name='upvote',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', True), ('session_key__isnull', False)), fields=('session_key', 'post'), name='unique_vote_per_session_post'),
        ),
        migrations.AddConstraint(
            model_name='upvote',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', True), ('session_key__isnull', False)), fields=('session_key', 'reply'), name='unique_vote_per_session_reply'),
        ),
    ]
