# Generated by Django 5.2.6 on 2025-10-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
