# Generated by Django 5.2.6 on 2025-10-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_upvote_unique_together_upvote_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
