# Generated by Django 5.2.7 on 2025-10-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
