# Generated by Django 5.2.7 on 2025-10-26 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('img_url', models.URLField(blank=True, max_length=500, null=True)),
                ('opening_hours_text', models.TextField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),

        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_hour', models.IntegerField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=10)),
                ('activity', models.CharField(blank=True, choices=[('ice_skating', 'Ice Skating'), ('ice_hockey', 'Ice Hockey'), ('curling', 'Curling')], max_length=50, null=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_arena.arena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('arena', 'date', 'start_hour')},
            },
        ),
    ]
