# Generated by Django 5.2.7 on 2025-10-25 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_arena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_arena.arena'),
        ),
        migrations.CreateModel(
            name='ArenaOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours_rules', to='booking_arena.arena')),
            ],
            options={
                'verbose_name': 'Opening Hour Rule',
                'verbose_name_plural': 'Opening Hours Rules',
                'ordering': ['arena', 'day'],
                'unique_together': {('arena', 'day')},
            },
        ),
    ]
