# Generated by Django 5.2.7 on 2025-10-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
