# Generated by Django 5.2.6 on 2025-12-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_arena', '0002_alter_booking_arena_arenaopeninghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenaopeninghours',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
