# Generated by Django 5.2.7 on 2025-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_arena', '0002_arena_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='opening_hours_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
